version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql_5_7_v1
    tty: true
    volumes:
      - mysql_db:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=spring_db
      - MYSQL_PASSWORD=nova
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

volumes:
  mysql_db:
